server:
  port: ${PORT:2222}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: ${SERVICE_NAME:survey-service}
  config:
    import: "optional:configserver:http://service-config:8760"
  cloud:
    config: # Ex) `http://service-config/auth/dev`
      name: survey # config name
      profile: ${SPRING_PROFILES_ACTIVE:dev}
  rabbitmq: # RabbitMQ 관련 설정
    host: rabbitmq
    port: 5672
    username: sweep
    password: sweep


management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: false
      percentiles:
        http:
          server:
            requests: 0.5, 0.9, 0.95, 0.99, 0.999
    tags:
      application: ${spring.application.name}